elbelleza/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("website.urls", namespace="website")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^about/$', views.about, name="about"),
    url(r'^models/$', views.models, name="models"),
]

website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

class HomepageSlideshow(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=150)
    image = models.FileField(max_length=150, upload_to="homepage-sliders", blank=True, null=True)
    content = RichTextField()

    def __str__(self):
        return self.title

class Model(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=150)
    gender = models.CharField(max_length=10, choices=(
        ("Male", "Male"),
        ("Female", "Female"),
        ("Transgender", "Transgender"),
    ), default="Female")
    date_of_birth = models.DateField(default=timezone.now)
    hometown = models.CharField(max_length=65, blank=True, null=True)
    country = models.CharField(max_length=50, default="India")
    about = RichTextField(blank=True, null=True)
    main_pic = models.FileField(max_length=150, upload_to="models/main-pics")

    def __str__(self):
        return self.name

class Images(models.Model):
    image = models.FileField(max_length=150, upload_to="models/extra-images")
    model = models.ForeignKey(Model, blank=True, null=True)


class Query(models.Model):
    date_added = models.DateField(default=timezone.now)
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    phone = models.BigIntegerField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class Testiomonial(models.Model):
    client_pic = models.FileField(upload_to="testiomonials/client-pics", blank=True, null=True)
    name = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    testiomonial = models.TextField()

    def __(str):
        return self.name

website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import HomepageSlideshow, Model

def index(request):
    homepage_sliders = HomepageSlideshow.objects.all()
    print homepage_sliders

    return render(request, "index.html", {
    "sliders":homepage_sliders,
    })

def contact(request):
    return render(request, "contact.html", {

    })

def about(request):
    models = Model.objects.all()

    return render(request, "about.html", {
    "models":models,
    })

def models(request):
    models = Model.objects.all()
    return render(request, "models.html", {
    "models":models,
    })

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">

<head>
		<meta charset=utf-8>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %}{% endblock title %} | El Belleza, Best Modelling Agency based in Delhi NCR, India</title>
		<meta name="keywords" content="">
		<meta name="description" content="">
		<link id="favicon" rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		<link rel="apple-touch-icon" sizes="144x144" href="images/favicon144.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/favicon114.png">
		<link rel="stylesheet" href="{% static "css/fonts.css" %}">
		<link rel="stylesheet" href="{% static "css/icon-font.css" %}">
		<link rel="stylesheet" href="{% static "css/social-icons.css" %}">
		<link rel="stylesheet" href="{% static "css/frontend-grid.css" %}">
		<link rel="stylesheet" href="{% static "js/owl.carousel/owl.carousel.css" %}">
		<link rel="stylesheet" href="{% static "css/style.css" %}">
		<link rel="stylesheet" href="{% static "css/mobile.css" %}">
		<!--[if IE]>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/mootools/1.4.0/mootools-yui-compressed.js" %}"></script>
		<script type="text/javascript" src="{% static "js/selectivizr-min.js" %}"></script>
		<script src="https://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js" %}"></script>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" %}"></script>
		<![endif]-->
	</head>

  <body>
		<div id="page">
			<!-- Page preloader -->
			<div id="page-preloader">
				<div class="spinner centered-container"></div>
			</div>
			<!-- END Page preloader -->

      {% include "menu.html" %}
			{% include "sidemenu.html" %}

      {% block content %}
      {% endblock content %}

      {% include "footer.html" %}

    </div>
      <script src="{% static "js/jquery-2.1.3.min.js" %}"></script>
    	<script src="{% static "js/owl.carousel/owl.carousel.min.js" %}"></script>
    	<script src="{% static "js/jquery.animateNumber.min.js" %}"></script>
    	<script src="{% static "js/script.js" %}"></script>

  </body>
</html>

templates/coming-soon.html
<!DOCTYPE HTML>
<html lang="en">
	
<!-- Mirrored from promo-theme.com/cropit/coming-soon.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 25 Jul 2017 06:39:33 GMT -->
<head>
		<meta charset=utf-8>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Crop It - photostudio HTML template</title>
		<meta name="keywords" content="">
		<meta name="description" content="">
		<link id="favicon" rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		<link rel="apple-touch-icon" sizes="144x144" href="images/favicon144.png">
		<link rel="apple-touch-icon" sizes="114x114" href="images/favicon114.png">
		<link rel="stylesheet" href="css/fonts.css">
		<link rel="stylesheet" href="css/icon-font.css">
		<link rel="stylesheet" href="css/social-icons.css">
		<link rel="stylesheet" href="css/frontend-grid.css">
		<link rel="stylesheet" href="js/owl.carousel/owl.carousel.css">
		<link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="css/mobile.css">
		<!--[if IE]>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/mootools/1.4.0/mootools-yui-compressed.js"></script>
		<script type="text/javascript" src="js/selectivizr-min.js"></script>
		<script src="https://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	<body>
		<div id="page">
			<!-- Page preloader -->
			<div id="page-preloader">
				<div class="spinner centered-container"></div>
			</div>
			<!-- END Page preloader -->
			<!-- Page header -->
			<header class="header dark-bg clearfix">
				<div class="fw-container">
					<div class="fw-main-row">
						<div class="fl logo-area"><a href="index.html"><img src="images/logo.png" class="logo-dark" alt="Crop It"><img src="images/logo-light.png" class="logo-light" alt="Crop It"></a></div>
						<div class="fr">
							<!-- Site navigation -->
							<nav class="navigation">
								<ul>
									<li class="menu-item-has-children">
										<a href="index.html">HOMe</a>
										<div class="sub-nav">
											<ul class="sub-menu">
												<li><a href="photographer.html">Photographer</a></li>
												<li><a href="photostudio.html">Photo Studio</a></li>
												<li><a href="photoschool.html">Photo School</a></li>
											</ul>
										</div>
									</li>
									<li class="current-menu-item menu-item-has-children">
										<a href="javascript:void(0);">PAGES</a>
										<div class="sub-nav">
											<ul class="sub-menu">
												<li><a href="about.html">About</a></li>
												<li><a href="typography.html">Typography</a></li>
												<li><a href="404.html">404 error</a></li>
												<li class="current-menu-item"><a href="coming-soon.html">Coming soon</a></li>
												<li class="menu-item-has-children">
													<a href="javascript:void(0);">Menu level</a>
													<div class="sub-nav">
														<ul class="sub-menu">
															<li class="menu-item-has-children">
																<a href="javascript:void(0);">Hyperlink 1</a>
																<div class="sub-nav">
																	<ul class="sub-menu">
																		<li><a href="javascript:void(0);">Hyperlink 1</a></li>
																		<li><a href="javascript:void(0);">Hyperlink 2</a></li>
																		<li><a href="javascript:void(0);">Hyperlink 3</a></li>
																		<li><a href="javascript:void(0);">Hyperlink 4</a></li>
																	</ul>
																</div>
															</li>
															<li class="menu-item-has-children">
																<a href="javascript:void(0);">Hyperlink 2</a>
																<div class="sub-nav">
																	<ul class="sub-menu">
																		<li><a href="javascript:void(0);">Hyperlink 1</a></li>
																		<li><a href="javascript:void(0);">Hyperlink 2</a></li>
																		<li><a href="javascript:void(0);">Hyperlink 3</a></li>
																		<li><a href="javascript:void(0);">Hyperlink 4</a></li>
																	</ul>
																</div>
															</li>
															<li><a href="javascript:void(0);">Hyperlink 3</a></li>
														</ul>
													</div>
												</li>
												<li><a href="services.html">Services</a></li>
											</ul>
										</div>
									</li>
									<li class="menu-item-has-children">
										<a href="javascript:void(0);">Gallery</a>
										<div class="sub-nav">
											<ul class="sub-menu">
												<li class="menu-item-has-children">
													<a href="javascript:void(0);">Grid</a>
													<div class="sub-nav">
														<ul class="sub-menu">
															<li><a href="grid-col2.html">Col 2</a></li>
															<li><a href="grid-col3.html">Col 3</a></li>
															<li><a href="grid-col4.html">Col 4</a></li>
														</ul>
													</div>
												</li>
												<li class="menu-item-has-children">
													<a href="javascript:void(0);">Masonry</a>
													<div class="sub-nav">
														<ul class="sub-menu">
															<li><a href="masonry-col2.html">Col 2</a></li>
															<li><a href="masonry-col3.html">Col 3</a></li>
															<li><a href="masonry-col4.html">Col 4</a></li>
														</ul>
													</div>
												</li>
												<li><a href="gallery-horizontal.html">Horizontal</a></li>
											</ul>
										</div>
									</li>
									<li class="menu-item-has-children">
										<a href="javascript:void(0);">Blog</a>
										<div class="sub-nav">
											<ul class="sub-menu">
												<li><a href="blog1.html">Variant 1</a></li>
												<li><a href="blog2.html">Variant 2</a></li>
											</ul>
										</div>
									</li>
									<li><a href="contact.html">CONTACT</a></li>
								</ul>
							</nav>
							<!-- END Site navigation -->
							<!-- Search module -->
							<div class="search-top">
								<form class="st-wrap">
									<input type="text" placeholder="Type and hit enter" name="search" class="input"><button class="st-button icon-font icon-search" type="submit"></button>
								</form>
							</div>
							<!-- END Search module -->
							<!-- Side area button -->
							<div class="side-area-btn">
								<div></div>
							</div>
							<!-- END Side area button -->
						</div>
					</div>
				</div>
			</header>
			<!-- END Page header -->
			<!-- Side panel -->
			<section class="side-panel dark-bg">
				<div class="close icon-font icon-cancel-1"></div>
				<header class="sp-top">
					<div class="logo-area"><a href="index.html"><img src="images/logo-light.png" class="logo-light" alt="Crop It"></a></div>
				</header>
				<div class="sp-wrap">
					<div>
						<h5 class="heading-decor2">gallery</h5>
						<!-- Gallery thumbnails -->
						<div class="gallery-module fw-row">
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img1.jpg" alt="gallery item 1"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img2.jpg" alt="gallery item 2"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img3.jpg" alt="gallery item 3"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img4.jpg" alt="gallery item 4"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img5.jpg" alt="gallery item 5"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img6.jpg" alt="gallery item 6"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img7.jpg" alt="gallery item 7"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img8.jpg" alt="gallery item 8"></a></div>
							<div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="images/imgs/gallery-module/img9.jpg" alt="gallery item 9"></a></div>
						</div>
						<h5 class="heading-decor2">contacts</h5>
						<!-- Contact rows -->
						<div class="contact-row">
							<div class="label">Address:</div>
							<div class="value">346A State Street, Brooklyn, NY 11217</div>
						</div>
						<div class="contact-row">
							<div class="label">Phone:</div>
							<div class="value">+1 (800) 123 45 67 - Office</div>
						</div>
						<div class="contact-row">
							<div class="label">Email:</div>
							<div class="value"><a href="mailto:support@promo-theme.com">support@promo-theme.com</a></div>
						</div>
						<!-- Social links -->
						<div class="social-links">
							<span>follow us:</span>
							<a href="javascript:void(0);"><i class="social-icons icon-facebook-logo"></i></a>
							<a href="javascript:void(0);"><i class="social-icons icon-instagram-social-network-logo-of-photo-camera"></i></a>
							<a href="javascript:void(0);"><i class="social-icons icon-twitter-logo"></i></a>
							<a href="javascript:void(0);"><i class="social-icons icon-pinterest-social-logo"></i></a>
							<a href="javascript:void(0);"><i class="social-icons icon-youtube-logotype"></i></a>
						</div>
						<h5 class="heading-decor2">stay in touch</h5>
						<!-- Subscribe form -->
						<form action="javascript:void(0);" class="subscribe-form"><input type="text" placeholder="enter your e-mail" class="input"><button type="submit" class="button-style1 white"><span>subscribe</span></button></form>
					</div>
				</div>
				<footer class="sp-bottom">Copyright © 2016 Promo-themes. All Rights Reserved.</footer>
			</section>
			<!-- END Side panel -->
			<!-- Full screen section -->
			<section class="full-screen dark-bg fw-main-row" style="background-image: url(images/imgs/coming-soon.jpg);">
				<div class="fw-container centered-container tac">
					<h1>Launching soon -<br>subscribe for updates</h1>
					<p><i>great temporary page while you are working on your full website</i></p>
					<form action="javascript:void(0);" class="subscribe-form"><input type="text" placeholder="Enter your e-mail" name="email" class="input"><button type="submit" class="button-style1"><span>subscribe</span></button></form>
				</div>
			</section>
			<!-- END Full screen section -->
		</div>
		<script src="js/jquery-2.1.3.min.js"></script>
		<script src="js/owl.carousel/owl.carousel.min.js"></script>
		<script src="js/script.js"></script>
	</body>

<!-- Mirrored from promo-theme.com/cropit/coming-soon.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 25 Jul 2017 06:39:53 GMT -->
</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="footer dark-bg">
  <div class="fw-container">
    <div class="fw-col-xs-12 fw-col-sm-6 fw-col-md-3">
      <div class="h5 heading-decor2">contacts</div>
      <!-- Contact rows -->
      <div class="contact-row">
        <div class="label">Address:</div>
        <div class="value">Bikhaji Cama Place, New Delhi </div>
      </div>
      <div class="contact-row">
        <div class="label">Phone:</div>
        <div class="value">+91 (11) 65000357 - Office</div>
      </div>
      <div class="contact-row">
        <div class="label">Email:</div>
        <div class="value"><a href="mailto:support@elbelleza.com">support@elbelleza.com</a></div>
      </div>
    </div>
    <div class="fw-col-xs-12 fw-col-sm-6 fw-col-md-3">
      <div class="h5 heading-decor2">gallery</div>
      <!-- Gallery thumbnails -->
      <div class="gallery-module fw-row">
        <div class="fw-col-xs-4 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img1.jpg" %}" alt="gallery item 1"></a></div>
        <div class="fw-col-xs-4 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img2.jpg" %}" alt="gallery item 2"></a></div>
        <div class="fw-col-xs-4 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img3.jpg" %}" alt="gallery item 3"></a></div>
        <div class="fw-col-xs-4 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img4.jpg" %}" alt="gallery item 4"></a></div>
        <div class="fw-col-xs-4 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img5.jpg" %}" alt="gallery item 5"></a></div>
        <div class="fw-col-xs-4 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img6.jpg" %}" alt="gallery item 6"></a></div>
      </div>
    </div>
    <div class="fw-col-xs-12 fw-col-sm-6 fw-col-md-2">
      <div class="h5 heading-decor2">LINKS</div>
      <!-- Footer nav -->
      <nav class="footer-nav">
        <ul>
          <li><a href="photographer.html">Home Page</a></li>
          <li><a href="about.html">About Us</a></li>
          <li><a href="services.html">Services</a></li>
          <li><a href="gallery1.html">Gallery</a></li>
          <li><a href="blog1.html">Blog</a></li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
      </nav>
    </div>
    <div class="fw-col-xs-12 fw-col-sm-6 fw-col-md-4">
      <div class="h5 heading-decor2">stay in touch</div>
      <!-- Subscribe form -->
      <form action="javascript:void(0);" class="subscribe-form"><input type="text" placeholder="Enter your e-mail" class="input"><button type="submit" class="button-style1"><span>subscribe</span></button></form>
      <!-- Social links -->
      <div class="social-links">
        <span>follow us:</span>
        <a href="javascript:void(0);"><i class="social-icons icon-facebook-logo"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-instagram-social-network-logo-of-photo-camera"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-twitter-logo"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-pinterest-social-logo"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-youtube-logotype"></i></a>
      </div>
    </div>
  </div>
</footer>
<!-- END Footer -->

templates/gallery1.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /cropit/gallery1.html was not found on this server.</p>
</body></html>

templates/sidemenu.html
{% load staticfiles %}

<section class="side-panel dark-bg">
  <div class="close icon-font icon-cancel-1"></div>
  <header class="sp-top">
    <div class="logo-area"><a href="{% url "website:index" %}"><img src="{% static "images/logo2-light.png" %}" class="logo-light" alt="Crop It"></a></div>
  </header>
  <div class="sp-wrap">
    <div>
      <h5 class="heading-decor2">gallery</h5>
      <!-- Gallery thumbnails -->
      <div class="gallery-module fw-row">
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img1.jpg" %}" alt="gallery item 1"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img2.jpg" %}" alt="gallery item 2"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img3.jpg" %}" alt="gallery item 3"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img4.jpg" %}" alt="gallery item 4"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img5.jpg" %}" alt="gallery item 5"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img6.jpg" %}" alt="gallery item 6"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img7.jpg" %}" alt="gallery item 7"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img8.jpg" %}" alt="gallery item 8"></a></div>
        <div class="fw-col-xs-6 fw-col-sm-4 item"><a href="javascript:void(0);"><img src="{% static "images/imgs/gallery-module/img9.jpg" %}" alt="gallery item 9"></a></div>
      </div>
      <h5 class="heading-decor2">contacts</h5>
      <!-- Contact rows -->
      <div class="contact-row">
        <div class="label">Address:</div>
        <div class="value">Bhikaji Cama Place, New Delhi</div>
      </div>
      <div class="contact-row">
        <div class="label">Phone:</div>
        <div class="value">+91 (11) 65000357 - Office</div>
      </div>
      <div class="contact-row">
        <div class="label">Email:</div>
        <div class="value"><a href="mailto:support@elbelleza.com">support@elbelleza.com</a></div>
      </div>
      <!-- Social links -->
      <div class="social-links">
        <span>follow us:</span>
        <a href="javascript:void(0);"><i class="social-icons icon-instagram-social-network-logo-of-photo-camera"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-facebook-logo"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-twitter-logo"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-pinterest-social-logo"></i></a>
        <a href="javascript:void(0);"><i class="social-icons icon-youtube-logotype"></i></a>
      </div>
      <h5 class="heading-decor2">stay in touch</h5>
      <!-- Subscribe form -->
      <form action="javascript:void(0);" class="subscribe-form"><input type="text" placeholder="enter your e-mail" class="input"><button type="submit" class="button-style1 white"><span>subscribe</span></button></form>
    </div>
  </div>
  <footer class="sp-bottom">Copyright © 2016 El Belleza Pvt. Ltd. All Rights Reserved. Designed by <a href="http://www.delhinerds.com">Delhi Nerds</a></footer>
</section>